<!DOCTYPE html>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->
<html>
    <head>
        <meta charset="UTF-8">
        <title></title>
    </head>
    <body>
		<p>The header of page</p>
		<?php
		// put your code here
		$this->getContent();
		?>
		<p>The footer of page</p>
    </body>
</html>
